/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "copyrightText": "©2010 John Einselen / Vectorform LLC",
    "done": "done",
    "download": "download",
    "drop": "drop image files here",
    "drop1": "drop image files here",
    "dropDetail": "512x512 or larger",
    "fail": "file processing failed\nplease try again",
    "feedback": "PNG files: 512, 114, 72, 57",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/iconifer",
    "locationText": "ImageMagick install location",
    "nameFileText": "file sheet prefix",
    "nameSpriteText": "sprite sheet suffix",
    "nameText": "sprite sheet suffix",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "optionsText": "flip over for more options",
    "outputText": "output files",
    "scaleText": "resize algorithm",
    "sharpAmount": "amount",
    "sharpSettings": "unsharp\nmask\nsettings",
    "sharpSize": "size",
    "sharpThresh": "threshold",
    "skip": "skip version",
    "success": "file processing successful, busy creating icons",
    "successDetails": "depending on image sizes\nthis could take a minute",
    "wrong": "wrong file format\nplease try again"
};




